### PR TITLE
Add "Mecha Ojama King" and "Mecha Ojama King Transformation"

### PR DESCRIPTION
**Pull request by SovietSIav**
https://yugipedia.com/wiki/Mecha_Ojama_King_Transformation
https://yugipedia.com/wiki/Mecha_Ojama_King
[Mecha Ojama King and Mecha Ojama King Transformation.zip](https://github.com/ProjectIgnis/BabelCDB/files/7204963/Mecha.Ojama.King.and.Mecha.Ojama.King.Transformation.zip)

### CODE REVIEW

**Comment by SovietSIav** [comment]
> https://yugipedia.com/wiki/Mecha_Ojama_King_Transformation
> https://yugipedia.com/wiki/Mecha_Ojama_King

Sorry, forgot the cdb files, 1 moment

**Comment by SovietSIav** [comment]
Sorry once again, it was like 2am so I made him a Fusion, lemme fix that

**Comment by SovietSIav** [comment]
Fixed it, edited the og pull

**Comment by pyrQ** [comment]
See https://github.com/ProjectIgnis/CardScripts/pull/656#issuecomment-924813419

**Pull request closed without merging**
